---
- name: Bootstrap and Loop New Users
  hosts: planetexpress:!farnsworth
  gather_facts: no

  vars_files:
          - vars/user1.yml
          - vars/user2.yml


  pre_tasks:
          - name: "update apt"
            raw: "apt update -y"
            become: yes

  tasks:
          - name: "bootstrap python and install"
            raw: "apt install python3-pip -y"
            become: yes
            ignore_errors: yes

          - name: create a new group omicronxii
            group:
                    name: omicronxii
                    state: present
            become: yes

          - name: add some users to new group
            user:
                    name: "{{ item }}"
                    comment: throw away users for testing
                    state: present
                    shell: /bin/bash
                    system: no
                    createhome: yes
                    group: omicronxii
            
            loop: "{{ martians + earthlings}}"

            become: yes
            
            register: results

          - name: Curious what is in results
            debug:
                    msg: "{{ item.home }}"
            loop: "{{ results.results }}"
            loop_control:
                    label: "{{ item.home }}"
                    
