---
- name: Our second playbook multi host
  hosts: planet-express
  gather_facts: yes # this is a default but we set it as a reminder to talk about
                    # this is also called setup module or setup.py
  tasks:
          - name: Manage some apps with apt
            apt:
                    state: present
                    name: sl
            become: yes
            when: ansible_os_family == "Debian"

          - name: Manage apps with yum
            yum:
                    name: s1
                    state: present
            become: yes
            when: ansible_os_family == "Redhat"


