---
- name: Bootstrapping a new user
  hosts: all
  gather_facts: yes
  
  vars:
          uid: 1999
          usertocreate: pumpkinking
          grouptocreate: halloween

  vars_files:
          # ~/pb03.yml       # zach says home directory is a secure space
                             # vars file will win over the vars defined in the playbook above
          - vars/pb03.yml
  
  tasks:
          ##- name: "ensure python is installed on target hosts"
          ## raw: "apt install -y python3-pip"
          ## become: yes


         - name: create a new group
           group:
                   name: "{{ grouptocreate }}"
                   state: present
           become: yes

         - name: Add "example user" with uid 1040 and group "sandbox"
           user:
                   name: "{{ usertocreate }}"
                   comment: "Trying to create a user"
                   state: present
                   shell: /bin/bash
                   system: no
                   createhome: yes
                   group: "{{ grouptocreate }}"
                   uid: "{{uid}}"
           become: yes
