---
- name: Set the EOS Banner
  connection: network_cli
  hosts: eosswitches
  gather_facts: no

  tasks:
          - name: Use the EOS banner to set a banner of the day
            eos_banner:
                     banner: login
                     text: Congrats on logging into the switch
                     state: absent
                     
            become: yes
